//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Tobias Schachte")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright © 2015-2024 Tobias Schachte")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("3.1.1882.3")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("3.1.1882.3+d7d83b413185a7cf31a0670ca08f3f33a2041a06")]
[assembly: System.Reflection.AssemblyProductAttribute("Macad|3D")]
[assembly: System.Reflection.AssemblyTitleAttribute("Macad.Interaction")]
[assembly: System.Reflection.AssemblyVersionAttribute("3.1.1882.3")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Test.Unit")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Test.Utils")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Test.Memory")]
[assembly: System.Runtime.Versioning.TargetPlatformAttribute("Windows7.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("Windows7.0")]

// 由 MSBuild WriteCodeFragment 类生成。

