#pragma checksum "..\..\..\..\..\Source\Macad.Presentation\Controls\TaskDialog\TaskDialog.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0DA518781C153C0AA869B8EFC391F98CBC0FBC7C"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using AvalonDock;
using AvalonDock.Controls;
using AvalonDock.Converters;
using AvalonDock.Layout;
using AvalonDock.Themes;
using Macad.Presentation;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Macad.Presentation {
    
    
    /// <summary>
    /// TaskDialog
    /// </summary>
    public partial class TaskDialog : Macad.Presentation.Dialog, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 30 "..\..\..\..\..\Source\Macad.Presentation\Controls\TaskDialog\TaskDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border ButtonsArea;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\..\..\Source\Macad.Presentation\Controls\TaskDialog\TaskDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ToggleButton ShowDetailsButton;
        
        #line default
        #line hidden
        
        
        #line 97 "..\..\..\..\..\Source\Macad.Presentation\Controls\TaskDialog\TaskDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox VerificationCheckBox;
        
        #line default
        #line hidden
        
        
        #line 109 "..\..\..\..\..\Source\Macad.Presentation\Controls\TaskDialog\TaskDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl Buttons;
        
        #line default
        #line hidden
        
        
        #line 133 "..\..\..\..\..\Source\Macad.Presentation\Controls\TaskDialog\TaskDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border FooterArea;
        
        #line default
        #line hidden
        
        
        #line 137 "..\..\..\..\..\Source\Macad.Presentation\Controls\TaskDialog\TaskDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border FooterInner;
        
        #line default
        #line hidden
        
        
        #line 145 "..\..\..\..\..\Source\Macad.Presentation\Controls\TaskDialog\TaskDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image FooterIcon;
        
        #line default
        #line hidden
        
        
        #line 149 "..\..\..\..\..\Source\Macad.Presentation\Controls\TaskDialog\TaskDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock FooterText;
        
        #line default
        #line hidden
        
        
        #line 154 "..\..\..\..\..\Source\Macad.Presentation\Controls\TaskDialog\TaskDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border FooterExpandedArea;
        
        #line default
        #line hidden
        
        
        #line 158 "..\..\..\..\..\Source\Macad.Presentation\Controls\TaskDialog\TaskDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border FooterExpandedInner;
        
        #line default
        #line hidden
        
        
        #line 161 "..\..\..\..\..\Source\Macad.Presentation\Controls\TaskDialog\TaskDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock FooterExpandedInfo;
        
        #line default
        #line hidden
        
        
        #line 167 "..\..\..\..\..\Source\Macad.Presentation\Controls\TaskDialog\TaskDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid LayoutRoot;
        
        #line default
        #line hidden
        
        
        #line 174 "..\..\..\..\..\Source\Macad.Presentation\Controls\TaskDialog\TaskDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border ContentArea;
        
        #line default
        #line hidden
        
        
        #line 180 "..\..\..\..\..\Source\Macad.Presentation\Controls\TaskDialog\TaskDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image MainIcon;
        
        #line default
        #line hidden
        
        
        #line 198 "..\..\..\..\..\Source\Macad.Presentation\Controls\TaskDialog\TaskDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock MainInstruction;
        
        #line default
        #line hidden
        
        
        #line 203 "..\..\..\..\..\Source\Macad.Presentation\Controls\TaskDialog\TaskDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ContentText;
        
        #line default
        #line hidden
        
        
        #line 206 "..\..\..\..\..\Source\Macad.Presentation\Controls\TaskDialog\TaskDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ContentExpandedInfo;
        
        #line default
        #line hidden
        
        
        #line 209 "..\..\..\..\..\Source\Macad.Presentation\Controls\TaskDialog\TaskDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ProgressBar ProgressBar;
        
        #line default
        #line hidden
        
        
        #line 216 "..\..\..\..\..\Source\Macad.Presentation\Controls\TaskDialog\TaskDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl CommandLinks;
        
        #line default
        #line hidden
        
        
        #line 230 "..\..\..\..\..\Source\Macad.Presentation\Controls\TaskDialog\TaskDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl RadioButtons;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.1.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Macad.Presentation;V3.1.1882.3;component/controls/taskdialog/taskdialog.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\Source\Macad.Presentation\Controls\TaskDialog\TaskDialog.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.1.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.1.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.ButtonsArea = ((System.Windows.Controls.Border)(target));
            return;
            case 2:
            this.ShowDetailsButton = ((System.Windows.Controls.Primitives.ToggleButton)(target));
            return;
            case 3:
            this.VerificationCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 4:
            this.Buttons = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 6:
            this.FooterArea = ((System.Windows.Controls.Border)(target));
            return;
            case 7:
            this.FooterInner = ((System.Windows.Controls.Border)(target));
            return;
            case 8:
            this.FooterIcon = ((System.Windows.Controls.Image)(target));
            return;
            case 9:
            this.FooterText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.FooterExpandedArea = ((System.Windows.Controls.Border)(target));
            return;
            case 11:
            this.FooterExpandedInner = ((System.Windows.Controls.Border)(target));
            return;
            case 12:
            this.FooterExpandedInfo = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.LayoutRoot = ((System.Windows.Controls.Grid)(target));
            return;
            case 14:
            this.ContentArea = ((System.Windows.Controls.Border)(target));
            return;
            case 15:
            this.MainIcon = ((System.Windows.Controls.Image)(target));
            return;
            case 16:
            this.MainInstruction = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 17:
            this.ContentText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 18:
            this.ContentExpandedInfo = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 19:
            this.ProgressBar = ((System.Windows.Controls.ProgressBar)(target));
            return;
            case 20:
            this.CommandLinks = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 21:
            this.RadioButtons = ((System.Windows.Controls.ItemsControl)(target));
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.1.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 5:
            
            #line 124 "..\..\..\..\..\Source\Macad.Presentation\Controls\TaskDialog\TaskDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NormalButton_Click);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

